version: 0.2
phases:
  build:
    commands:
      - IMAGE_URI=$(cat imageDetail.json | python3 -c "import sys,json;print(json.load(sys.stdin)['ImageURI'])") && printf '[{"name":"springboot-cloudwatch-example","imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
